### ISSUE TITLE
Filter update isn't working correctly

### ISSUE THREAD

**Issue by mustii82** [el1t/uBlock-Safari#1]
I can't update the Filters. I get a wear full progress bar and after that the plugin page is freezing and even after a restart the plugin has stopped working for me so i can see ads everywhere.

**Comment by LRFLEW** [comment]
I'll put my experience here, as it's probably the same issue.

When I was updating the filters, I had the entire browser crash on me multiple times. I didn't have the window in focus, as I was doing other things while I was updating them, so I don't know what it was doing at the time of the crash(es), nor do I know if it happens if the window is in focus. The crashes did seem to allow some progress to be made, as it now has *most* filters up to date, with the exception of EasyList saying it's out of date despite multiple (non-crashing) attempts to update it.

Some basic information about what I'm running. Let me know if you need any other info:

macOS Version: 10.12.1
Safari Version: 10.0.1
Other Extensions:
* Reddit Enhancement Suite 5.0.2 (maybe a different 5.0.X version)
* BetterTTV 6.8
* I had uBlock (non-origin) 0.9.5.2 disabled, but not uninstalled (don't know if that could have affected it)
* Tampermonkey 4.2 with the following scripts installed:
  * Anti-Adblock Killer | Reek 10.0
  * FrankerFaceZ 1.58
  * YouTube Center Developer Build 538
