### ISSUE TITLE
Can't "download and open" on iPad with iOS 11

### ISSUE THREAD

**Issue by erAck** [el1t/uBlock-Safari#95]
It may be that I'm just too dumb for this because I have no clue about iPads (then close the issue), but tried what's given as installation instructions there seems to be no way to download and "open the downloaded extension" in Safari. So how does one install the extension on an iPad with iOS 11?

**Comment by danmcquade** [comment]
This extension is for Safari on macOS (OS X). It is not compatible with mobile Safari on iOS.

**Comment by vassudanagunta** [comment]
You can't. iOS does not support Safari extensions. iOS does support [App Extensions](https://developer.apple.com/app-extensions/), but they are very limited and certainly don't allow what uBlock Origin does. 

But Safari iOS does support [Content Blockers](https://www.macworld.com/article/2984483/ios/hands-on-with-content-blocking-safari-extensions-in-ios-9.html). Just don't install Purify as it is made by a dishonest person, the same guy who accepts donations for uBlock as if he is the guy who created it and as if he is keeping it up to date (He hasn't updated the code in over 3 years, not even stealing more of @gorhill's excellent work).

Which, btw, leads me to a question I've been wanting to ask @gorhill and @el1t: Does uBlock Origin even make sense for Safari anymore since both the macOS and iOS versions support Safari Content Blockers, which I understand are implemented in the most efficient way possible? I have been so loyal to uBLock Origin that I haven't even tried.

**Comment by vassudanagunta** [comment]
Also please close this issue. The maintainer is busy enough as it is!

**Comment by yuusharo** [comment]
@vassudanagunta In my experience, Content Blockers on Safari are flaky and unstable, or at least the extensions I've tried are like that. Safari balks if you try to load more than 50,000 rules (EasyList alone exceeds that), and I've had many pages crash and reload themselves, particularly on script heavy pages like legacy Twitch.TV channels.

Content blockers work incredibly well on iOS (I use 1Blocker myself), but I vastly prefer Ublock Origin on macOS Safari any day. It's been rock solid in my day-to-day use.

**Comment by Baccount** [comment]
@vassudanagunta  I also use 1Blocker on iOS and it’s great.

**Comment by erAck** [comment]
Thanks, also for pointing to 1Blocker. Closing this issue.
